"use client";

import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  FiCalendar,
  FiCheckCircle,
  FiClock,
  FiRefreshCw,
  FiSave,
  FiSend,
  FiSliders,
} from "react-icons/fi";
import { Button } from "@/components/Common/Button";
import CustomInput from "@/components/Common/inputField";
import StatusBadge from "@/components/Common/StatusBadge";
import ToggleButton from "@/components/Common/ToggleButton";
import { ToasterUtils } from "@/components/ui/toast";
import {
  AutomationRule,
  createAutomationRule,
  getAutomationRules,
  getAutomationTemplates,
  seedAutomationDefaults,
  updateAutomationRule,
} from "@/services/automations";
import { getWhatsappTemplates, syncWhatsappTemplates, type WhatsappTemplate } from "@/services/templates";

type TemplateSource = "whatsapp" | "automation" | "text";

type CampaignDefinition = {
  key: string;
  title: string;
  trigger: string;
  description: string;
  timingLabel: string;
  defaultDelayHours: number;
  category: "event" | "seasonal" | "custom";
  defaultBody: string;
  variables: string[];
  readyNote: string;
};

const CAMPAIGNS: CampaignDefinition[] = [
  {
    key: "order_created",
    title: "Order Confirmation",
    trigger: "order_created",
    description: "Confirm a new Shopify order as soon as it is created.",
    timingLabel: "Immediately after order creation",
    defaultDelayHours: 0,
    category: "event",
    defaultBody:
      "Hi {{customer_name}}, your order {{order_number}} is confirmed. Total amount is {{total}} {{currency}}.",
    variables: ["customer_name", "order_number", "total", "currency"],
    readyNote: "Uses Shopify order webhook/sync events.",
  },
  {
    key: "cod_verification",
    title: "COD Verification",
    trigger: "cod_verification",
    description: "Verify cash-on-delivery orders before fulfillment.",
    timingLabel: "Immediately after COD order is created",
    defaultDelayHours: 0,
    category: "event",
    defaultBody:
      "Hi {{customer_name}}, please reply YES to confirm your COD order {{order_number}} worth {{total}} {{currency}}.",
    variables: ["customer_name", "order_number", "total", "currency"],
    readyNote: "Best used with a utility template and confirmation keyword handling.",
  },
  {
    key: "cart_abandoned",
    title: "Cart Abandoned",
    trigger: "cart_abandoned",
    description: "Reminder after a Shopify checkout is left incomplete.",
    timingLabel: "24 hours after checkout is abandoned",
    defaultDelayHours: 24,
    category: "event",
    defaultBody: "Hi {{customer_name}}, you left items in your cart. Tap the button below to complete your order.",
    variables: ["customer_name", "cart_url", "total", "currency"],
    readyNote: "Uses Shopify abandoned checkout sync/webhook.",
  },
  {
    key: "browse_no_buy",
    title: "Browse No Buy",
    trigger: "browse_no_buy",
    description: "Follow up when a shopper browses products but does not click or buy.",
    timingLabel: "Usually 15 minutes to 3 days after product browse",
    defaultDelayHours: 72,
    category: "event",
    defaultBody: "Still thinking it over, {{customer_name}}? Reply YES and I will bring back the products you viewed.",
    variables: ["customer_name"],
    readyNote: "Uses product browse events generated by WhatsApp catalog/carousel views.",
  },
  {
    key: "order_shipped",
    title: "Shipping Update",
    trigger: "order_shipped",
    description: "Notify the customer when an order ships.",
    timingLabel: "Immediately after shipment/fulfillment event",
    defaultDelayHours: 0,
    category: "event",
    defaultBody:
      "Good news {{customer_name}}, your order {{order_number}} has shipped. Tap the button below to track your order.",
    variables: ["customer_name", "order_number"],
    readyNote: "Uses Shopify fulfillment/shipping events.",
  },
  {
    key: "post_dispatch_cross_sell",
    title: "Post-dispatch Cross-sell",
    trigger: "post_dispatch_cross_sell",
    description: "Recommend matching products after dispatch.",
    timingLabel: "1 day after shipment",
    defaultDelayHours: 24,
    category: "event",
    defaultBody: "Your {{product_name}} is on the way. Reply YES to see matching picks.",
    variables: ["customer_name", "product_name"],
    readyNote: "Useful for accessories and complementary items.",
  },
  {
    key: "delivered_review",
    title: "Order Delivered",
    trigger: "delivered_review",
    description: "Ask for a review after the order is delivered.",
    timingLabel: "1 day after delivered event",
    defaultDelayHours: 24,
    category: "event",
    defaultBody: "Hi {{customer_name}}, hope you are enjoying order {{order_number}}. Reply with a rating from 1 to 5.",
    variables: ["customer_name", "order_number"],
    readyNote: "Runs when delivered follow-up events are queued by the backend.",
  },
  {
    key: "feedback_request",
    title: "Feedback Request",
    trigger: "feedback_request",
    description: "Ask for simple feedback after delivery or support completion.",
    timingLabel: "1 day after the feedback event",
    defaultDelayHours: 24,
    category: "event",
    defaultBody: "Hi {{customer_name}}, how was your experience with order {{order_number}}? Reply with a rating from 1 to 5.",
    variables: ["customer_name", "order_number"],
    readyNote: "Can be triggered from delivered/order follow-up events.",
  },
  {
    key: "replenishment",
    title: "Replenishment",
    trigger: "replenishment",
    description: "Bring customers back after a product usage cycle.",
    timingLabel: "90 days after purchase/delivery event",
    defaultDelayHours: 2160,
    category: "event",
    defaultBody: "Hi {{customer_name}}, running low on {{product_name}}? Reply YES to reorder or see refills.",
    variables: ["customer_name", "product_name"],
    readyNote: "Best for repeat-use products once purchase events include product_name.",
  },
  {
    key: "special_campaign",
    title: "Special Campaign",
    trigger: "special_campaign",
    description: "Reusable custom event campaign for store-specific journeys.",
    timingLabel: "Manual/custom event trigger",
    defaultDelayHours: 0,
    category: "custom",
    defaultBody: "Hi {{customer_name}}, we have a special update for you. Reply YES to know more.",
    variables: ["customer_name"],
    readyNote: "Use for a custom backend event. Date-based broadcast campaigns need a separate scheduler.",
  },
];

const SAMPLE_VALUES: Record<string, string> = {
  customer_name: "Riya",
  order_number: "#5967",
  cart_url: "https://store/cart/abc123",
  cart_token: "abc123",
  total: "1099",
  currency: "INR",
  product_name: "Airtight Glass Jar",
};

function formatDelay(seconds?: number) {
  const value = Number(seconds || 0);
  if (!value) return "Immediately";
  if (value < 3600) return `${Math.round(value / 60)} min`;
  if (value < 86400) return `${Math.round(value / 3600)} hr`;
  const days = Math.round(value / 86400);
  return `${days} day${days === 1 ? "" : "s"}`;
}

function getTemplateBody(template?: WhatsappTemplate) {
  const components = Array.isArray(template?.components) ? template?.components : [];
  const body = components.find((component) => String(component?.type || "").toUpperCase() === "BODY");
  const templateRecord = template as (WhatsappTemplate & { body?: string; format?: string }) | undefined;
  return String(body?.text || templateRecord?.body || templateRecord?.format || "");
}

function getTemplateVariableKeys(text: string) {
  return Array.from(new Set(Array.from(text.matchAll(/\{\{\s*([a-zA-Z0-9_.-]+)\s*\}\}/g)).map((match) => match[1])));
}

function previewText(text: string, variables: string[]) {
  let output = text || "Select or write a template to preview.";
  variables.forEach((variable, index) => {
    output = output.replaceAll(`{{${variable}}}`, SAMPLE_VALUES[variable] || `Sample ${variable}`);
    output = output.replaceAll(`{{${index + 1}}}`, SAMPLE_VALUES[variable] || `Sample ${variable}`);
  });
  return output;
}

function findRule(rules: AutomationRule[], campaign: CampaignDefinition) {
  return (
    rules.find((rule) => rule.trigger === campaign.trigger && rule.name === campaign.title) ||
    rules.find((rule) => rule.trigger === campaign.trigger)
  );
}

export default function CampaignsPage() {
  const queryClient = useQueryClient();
  const [selectedKey, setSelectedKey] = useState(CAMPAIGNS[0].key);
  const [templateSource, setTemplateSource] = useState<TemplateSource>("whatsapp");
  const [selectedTemplateId, setSelectedTemplateId] = useState("");
  const [campaignName, setCampaignName] = useState(CAMPAIGNS[0].title);
  const [delayHours, setDelayHours] = useState(String(CAMPAIGNS[0].defaultDelayHours));
  const [enabled, setEnabled] = useState(true);
  const [customBody, setCustomBody] = useState(CAMPAIGNS[0].defaultBody);

  const selectedCampaign = CAMPAIGNS.find((campaign) => campaign.key === selectedKey) || CAMPAIGNS[0];

  const rulesQuery = useQuery({
    queryKey: ["campaign-automation-rules"],
    queryFn: getAutomationRules,
  });

  const automationTemplatesQuery = useQuery({
    queryKey: ["campaign-automation-templates"],
    queryFn: getAutomationTemplates,
  });

  const whatsappTemplatesQuery = useQuery({
    queryKey: ["campaign-whatsapp-templates"],
    queryFn: () =>
      getWhatsappTemplates({
        status: "APPROVED",
        limit: 100,
      }),
  });

  const seedMutation = useMutation({
    mutationFn: seedAutomationDefaults,
    onSuccess: () => {
      ToasterUtils.success("Default automations are ready");
      queryClient.invalidateQueries({ queryKey: ["campaign-automation-rules"] });
      queryClient.invalidateQueries({ queryKey: ["campaign-automation-templates"] });
    },
    onError: () => ToasterUtils.error("Unable to seed automation defaults"),
  });

  const syncTemplatesMutation = useMutation({
    mutationFn: syncWhatsappTemplates,
    onSuccess: () => {
      ToasterUtils.success("Templates synced");
      queryClient.invalidateQueries({ queryKey: ["campaign-whatsapp-templates"] });
    },
    onError: () => ToasterUtils.error("Template sync failed"),
  });

  const saveMutation = useMutation({
    mutationFn: async () => {
      const rule = activeRule;
      const parsedHours = Math.max(0, Number(delayHours) || 0);
      const basePayload = {
        name: campaignName.trim() || selectedCampaign.title,
        trigger: selectedCampaign.trigger,
        delay_seconds: Math.round(parsedHours * 3600),
        enabled,
        conditions: { campaign_key: selectedCampaign.key },
      };
      const templatePayload =
        templateSource === "whatsapp"
          ? {
              whatsapp_template_id: selectedTemplateId ? Number(selectedTemplateId) : null,
              message_template_id: null,
              message_body: null,
            }
          : templateSource === "automation"
            ? {
                message_template_id: selectedTemplateId ? Number(selectedTemplateId) : null,
                whatsapp_template_id: null,
                message_body: null,
              }
            : {
                message_template_id: null,
                whatsapp_template_id: null,
                message_body: customBody.trim() || selectedCampaign.defaultBody,
              };

      if (rule) {
        return updateAutomationRule({ ruleId: rule.id, ...basePayload, ...templatePayload });
      }
      return createAutomationRule({ ...basePayload, ...templatePayload });
    },
    onSuccess: () => {
      ToasterUtils.success("Campaign saved");
      queryClient.invalidateQueries({ queryKey: ["campaign-automation-rules"] });
      queryClient.invalidateQueries({ queryKey: ["campaign-automation-templates"] });
    },
    onError: () => ToasterUtils.error("Unable to save campaign"),
  });

  const rules = rulesQuery.data || [];
  const automationTemplates = automationTemplatesQuery.data || [];
  const whatsappTemplates = whatsappTemplatesQuery.data?.data || [];
  const activeRule = findRule(rules, selectedCampaign);

  const selectedWhatsappTemplate = useMemo(
    () => whatsappTemplates.find((template) => String(template.id) === selectedTemplateId),
    [selectedTemplateId, whatsappTemplates],
  );
  const selectedAutomationTemplate = useMemo(
    () => automationTemplates.find((template) => String(template.id) === selectedTemplateId),
    [selectedTemplateId, automationTemplates],
  );

  useEffect(() => {
    const rule = findRule(rules, selectedCampaign);
    setCampaignName(rule?.name || selectedCampaign.title);
    setDelayHours(String(Math.round((rule?.delay_seconds ?? selectedCampaign.defaultDelayHours * 3600) / 3600)));
    setEnabled(rule ? Boolean(rule.enabled) : true);
    setCustomBody(rule?.message_body || selectedCampaign.defaultBody);

    if (rule?.message_template_id) {
      setTemplateSource("automation");
      setSelectedTemplateId(String(rule.message_template_id));
    } else {
      setTemplateSource("whatsapp");
      setSelectedTemplateId("");
    }
  }, [selectedCampaign, rules]);

  const sourceBody =
    templateSource === "whatsapp"
      ? getTemplateBody(selectedWhatsappTemplate)
      : templateSource === "automation"
        ? selectedAutomationTemplate?.body || ""
        : customBody;
  const previewBody = sourceBody || selectedCampaign.defaultBody;
  const variableKeys = getTemplateVariableKeys(previewBody);
  const canSave =
    templateSource === "text" ? Boolean(customBody.trim()) : Boolean(selectedTemplateId);

  return (
    <div className="mx-auto max-w-7xl space-y-6">
      <section className="border-b border-default pb-4">
        <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
          <div>
            <h1 className="text-2xl font-semibold text-foreground">WhatsApp Automation Campaigns</h1>
            <p className="mt-2 text-sm text-muted">
              Connect Shopify events, approved templates, and send timing from one place.
            </p>
          </div>
          <div className="flex flex-col gap-2 sm:flex-row">
            <Button
              text="Sync Templates"
              icon={FiRefreshCw}
              variant="outline"
              color="surface"
              onClick={() => syncTemplatesMutation.mutate()}
              loading={syncTemplatesMutation.isPending}
              disabled={syncTemplatesMutation.isPending}
              fullWidthOnMobile
            />
            <Button
              text="Seed Defaults"
              icon={FiCheckCircle}
              variant="outline"
              color="surface"
              onClick={() => seedMutation.mutate()}
              loading={seedMutation.isPending}
              disabled={seedMutation.isPending}
              fullWidthOnMobile
            />
          </div>
        </div>
      </section>

      <section className="grid gap-6 lg:grid-cols-[330px_minmax(0,1fr)]">
        <div className="space-y-3">
          {CAMPAIGNS.map((campaign) => {
            const rule = findRule(rules, campaign);
            const selected = campaign.key === selectedKey;
            return (
              <button
                key={campaign.key}
                type="button"
                onClick={() => setSelectedKey(campaign.key)}
                className={`w-full rounded-md border px-4 py-3 text-left transition ${
                  selected ? "border-primary bg-primary/5" : "border-default bg-surface hover:bg-surface-hover"
                }`}
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="font-semibold text-foreground">{campaign.title}</p>
                    <p className="mt-1 text-xs leading-5 text-muted">{campaign.description}</p>
                    <p className="mt-2 text-xs text-muted">{campaign.timingLabel}</p>
                  </div>
                  <StatusBadge
                    status={rule?.enabled ? "Active" : rule ? "Inactive" : "Pending"}
                    displayText={rule?.enabled ? "Live" : rule ? "Paused" : "Setup"}
                    className="cursor-default"
                  />
                </div>
              </button>
            );
          })}
        </div>

        <div className="space-y-6">
          <section className="rounded-lg border border-default bg-surface p-5">
            <div className="flex flex-col gap-4 border-b border-default pb-4 md:flex-row md:items-start md:justify-between">
              <div>
                <h2 className="text-lg font-semibold text-foreground">{selectedCampaign.title}</h2>
                <p className="mt-1 text-sm text-muted">{selectedCampaign.description}</p>
                <p className="mt-2 text-xs text-muted">{selectedCampaign.readyNote}</p>
              </div>
              <div className="inline-flex items-center gap-3">
                <ToggleButton isOn={enabled} size="sm" onToggle={() => setEnabled((value) => !value)} />
                <StatusBadge
                  status={enabled ? "Active" : "Inactive"}
                  displayText={enabled ? "Enabled" : "Paused"}
                  className="cursor-default"
                />
              </div>
            </div>

            <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]">
              <div className="space-y-5">
                <CustomInput
                  label="Campaign name"
                  value={campaignName}
                  onChange={setCampaignName}
                  placeholder={selectedCampaign.title}
                />

                <div className="grid gap-4 md:grid-cols-2">
                  <CustomInput
                    label="Send after"
                    type="number"
                    min="0"
                    value={delayHours}
                    onChange={setDelayHours}
                    helperText={`Current delay: ${formatDelay(Number(delayHours || 0) * 3600)}`}
                  />
                  <div className="flex flex-col gap-1">
                    <label className="mb-0.5 text-sm font-medium text-gray-800">Template source</label>
                    <select
                      value={templateSource}
                      onChange={(event) => {
                        setTemplateSource(event.target.value as TemplateSource);
                        setSelectedTemplateId("");
                      }}
                      className="h-[45px] rounded-[5px] border border-gray-300 bg-white px-3 text-sm text-[#0d0c22] outline-none focus:border-[#818cf8] focus:ring-[3px] focus:ring-[#818cf8]/30"
                    >
                      <option value="whatsapp">Approved WhatsApp templates</option>
                      <option value="automation">Automation templates</option>
                      <option value="text">Plain text fallback</option>
                    </select>
                  </div>
                </div>

                {templateSource === "text" ? (
                  <div className="flex flex-col gap-1">
                    <label className="mb-0.5 text-sm font-medium text-gray-800">Message body</label>
                    <textarea
                      value={customBody}
                      onChange={(event) => setCustomBody(event.target.value)}
                      rows={5}
                      className="rounded-[5px] border border-gray-300 bg-white px-3 py-2 text-sm text-[#0d0c22] outline-none focus:border-[#818cf8] focus:ring-[3px] focus:ring-[#818cf8]/30"
                    />
                    <p className="text-xs text-muted">Use variables like {selectedCampaign.variables.map((item) => `{{${item}}}`).join(", ")}.</p>
                  </div>
                ) : (
                  <div className="flex flex-col gap-1">
                    <label className="mb-0.5 text-sm font-medium text-gray-800">Template</label>
                    <select
                      value={selectedTemplateId}
                      onChange={(event) => setSelectedTemplateId(event.target.value)}
                      className="h-[45px] rounded-[5px] border border-gray-300 bg-white px-3 text-sm text-[#0d0c22] outline-none focus:border-[#818cf8] focus:ring-[3px] focus:ring-[#818cf8]/30"
                    >
                      <option value="">
                        {templateSource === "whatsapp" ? "Select approved WhatsApp template" : "Select automation template"}
                      </option>
                      {templateSource === "whatsapp"
                        ? whatsappTemplates.map((template) => (
                            <option key={template.id} value={template.id}>
                              {template.name} - {template.language}
                            </option>
                          ))
                        : automationTemplates.map((template) => (
                            <option key={template.id} value={template.id}>
                              {template.name} - {template.language}
                            </option>
                          ))}
                    </select>
                  </div>
                )}

                <div className="grid gap-3 md:grid-cols-3">
                  <InfoTile icon={FiSliders} label="Trigger" value={selectedCampaign.trigger} />
                  <InfoTile icon={FiClock} label="Delay" value={formatDelay(Number(delayHours || 0) * 3600)} />
                  <InfoTile icon={FiCalendar} label="Type" value={selectedCampaign.category} />
                </div>

                <div className="flex justify-end">
                  <Button
                    text={activeRule ? "Save Campaign" : "Create Campaign"}
                    icon={FiSave}
                    onClick={() => saveMutation.mutate()}
                    loading={saveMutation.isPending}
                    disabled={saveMutation.isPending || !canSave}
                    fullWidthOnMobile
                  />
                </div>
              </div>

              <aside className="rounded-md border border-default bg-surface-strong p-4">
                <div className="flex items-center gap-2 text-sm font-semibold text-foreground">
                  <FiSend className="h-4 w-4" />
                  Message preview
                </div>
                <div className="mt-4 rounded-md bg-white p-4 text-sm leading-6 text-foreground shadow-sm">
                  {previewText(previewBody, variableKeys.length ? variableKeys : selectedCampaign.variables)}
                </div>
                <dl className="mt-4 space-y-2 text-xs text-muted">
                  <div className="flex justify-between gap-3">
                    <dt>Rule</dt>
                    <dd className="font-medium text-foreground">{activeRule ? `#${activeRule.id}` : "New"}</dd>
                  </div>
                  <div className="flex justify-between gap-3">
                    <dt>Variables</dt>
                    <dd className="max-w-[220px] text-right font-medium text-foreground">
                      {(variableKeys.length ? variableKeys : selectedCampaign.variables).join(", ") || "None"}
                    </dd>
                  </div>
                  <div className="flex justify-between gap-3">
                    <dt>Status</dt>
                    <dd className="font-medium text-foreground">{enabled ? "Enabled" : "Paused"}</dd>
                  </div>
                </dl>
              </aside>
            </div>
          </section>
        </div>
      </section>
    </div>
  );
}

function InfoTile({ icon: Icon, label, value }: { icon: typeof FiClock; label: string; value: string }) {
  return (
    <div className="rounded-md border border-default bg-white px-3 py-2">
      <div className="flex items-center gap-2 text-xs text-muted">
        <Icon className="h-3.5 w-3.5" />
        {label}
      </div>
      <p className="mt-1 truncate text-sm font-semibold text-foreground">{value}</p>
    </div>
  );
}
