export const ROUTES = {
  dashboard: "/dashboard",
  liveChat: "/live-chat",
  comingSoon: "/coming-soon",
  contacts: "/contacts",
  profile: "/profile",
  templateLibrary: "/template-library",
  templateMessage: "/template-message",
  campaigns: "/campaigns",
  supportTickets: "/support-tickets",
  whatsappBot: "/whatsapp-bot",
  botSettings: "/bot-settings",
  knowledgeBase: "/knowledge-base",
  handoffRules: "/handoff-rules",
  whatsappAnalytics: "/whatsapp-analytics",
  ecommerce: "/ecommerce",
  onboarding: "/onboarding",
  flows: "/coming-soon",
  shopifyIntegration: "/shopify-integration",
} as const;
