export const ROUTES = {
  dashboard: "/dashboard",
  liveChat: "/live-chat",
  comingSoon: "/coming-soon",
  contacts: "/contacts",
  profile: "/profile",
  templateMessage: "/template-message",
  campaigns: "/campaigns",
  supportTickets: "/support-tickets",
  whatsappBot: "/whatsapp-bot",
  botSettings: "/bot-settings",
  knowledgeBase: "/knowledge-base",
  handoffRules: "/handoff-rules",
  automationSettings: "/automation-settings",
  botLogs: "/bot-logs",
  whatsappAnalytics: "/whatsapp-analytics",
  aiAgentApis: "/ai-agent-apis",
  ecommerce: "/ecommerce",
  onboarding: "/onboarding",
  compliance: "/compliance",
  agency: "/agency",
  flows: "/coming-soon",
  shopifyIntegration: "/shopify-integration",
  woocommerceIntegration: "/woocommerce-integration",
} as const;
