import type { IconType } from "react-icons";
import { BiMessageRoundedDots, BiRefresh } from "react-icons/bi";
import {
  FiActivity,
  FiAlertCircle,
  FiAlertTriangle,
  FiArrowDown,
  FiArrowDownLeft,
  FiArrowLeft,
  FiArrowRight,
  FiArrowUp,
  FiArrowUpRight,
  FiBarChart2,
  FiBold,
  FiBookOpen,
  FiCalendar,
  FiCamera,
  FiCheckCircle,
  FiCheck,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiClock,
  FiCode,
  FiCopy,
  FiCpu,
  FiDatabase,
  FiDollarSign,
  FiEdit2,
  FiExternalLink,
  FiEye,
  FiEyeOff,
  FiFile,
  FiFileText,
  FiFilter,
  FiGlobe,
  FiHome,
  FiImage,
  FiInfo,
  FiItalic,
  FiList,
  FiLoader,
  FiLock,
  FiMail,
  FiMapPin,
  FiMenu,
  FiMessageCircle,
  FiMessageSquare,
  FiMoreVertical,
  FiMousePointer,
  FiPhone,
  FiPaperclip,
  FiPlay,
  FiPlus,
  FiRefreshCw,
  FiRotateCcw,
  FiSave,
  FiSearch,
  FiSend,
  FiSettings,
  FiShare2,
  FiShield,
  FiShoppingBag,
  FiSliders,
  FiSmile,
  FiTag,
  FiTarget,
  FiTrash2,
  FiTrendingUp,
  FiTruck,
  FiUser,
  FiUserCheck,
  FiUsers,
  FiX,
  FiZap,
} from "react-icons/fi";
import { MdCampaign, MdContacts, MdPerson, MdPhoto } from "react-icons/md";
import { IoCheckmarkDone, IoMicOutline } from "react-icons/io5";
import { LuPanelTopOpen } from "react-icons/lu";
import {
    RiArrowUpLine,
  RiDashboardLine,
  RiDatabase2Line,
  RiFlowChart,
  RiMoonLine,
  RiNotification3Line,
  RiSendPlaneLine,
  RiSettings3Line,
  RiSunLine,
    RiTerminalBoxLine,
  RiWhatsappLine,
} from "react-icons/ri";
import { SiBitcoin, SiShopify, SiWoo } from "react-icons/si";
import * as mdi from "@mdi/js";

type IconEntry = string | IconType;

export const iconMap: Record<string, IconEntry> = {
  // Material Design Icons
  "mdi:speedometer": mdi.mdiSpeedometer,

  // Remix Icons
  "ri:dashboard-line": RiDashboardLine,
  "ri:database-2-line": RiDatabase2Line,
  "ri:flow-chart": RiFlowChart,
  "ri:moon-line": RiMoonLine,
  "ri:send-plane-line": RiSendPlaneLine,
  "ri:notification-3-line": RiNotification3Line,
  "ri:settings-3-line": RiSettings3Line,
  "ri:sun-line": RiSunLine,
  "ri:arrow-up-line": RiArrowUpLine,
  "ri:terminal-box-line": RiTerminalBoxLine,
  "ri:whatsapp-line": RiWhatsappLine,

  // Boxicons
  "bi:message-rounded-dots": BiMessageRoundedDots,
  "bi:refresh": BiRefresh,

  // Material icons
  "md:contacts": MdContacts,
  "md:campaign": MdCampaign,
  "md:person": MdPerson,
  "md:photo": MdPhoto,

  // Ionicons
  "io:checkmark-done": IoCheckmarkDone,
  "io:mic-outline": IoMicOutline,

  // Lucide icons
  "lu:panel-top-open": LuPanelTopOpen,

  // Feather icons
  "fi:activity": FiActivity,
  "fi:alert-circle": FiAlertCircle,
  "fi:alert-triangle": FiAlertTriangle,
  "fi:arrow-down": FiArrowDown,
  "fi:arrow-down-left": FiArrowDownLeft,
  "fi:arrow-left": FiArrowLeft,
  "fi:arrow-right": FiArrowRight,
  "fi:arrow-up": FiArrowUp,
  "fi:arrow-up-right": FiArrowUpRight,
  "fi:camera": FiCamera,
  "fi:bar-chart-2": FiBarChart2,
  "fi:bold": FiBold,
  "fi:book-open": FiBookOpen,
  "fi:calendar": FiCalendar,
  "fi:check-circle": FiCheckCircle,
  "fi:check": FiCheck,
  "fi:chevron-down": FiChevronDown,
  "fi:chevron-left": FiChevronLeft,
  "fi:chevron-right": FiChevronRight,
  "fi:clock": FiClock,
  "fi:code": FiCode,
  "fi:copy": FiCopy,
  "fi:cpu": FiCpu,
  "fi:database": FiDatabase,
  "fi:dollar-sign": FiDollarSign,
  "fi:edit-2": FiEdit2,
  "fi:external-link": FiExternalLink,
  "fi:eye": FiEye,
  "fi:eye-off": FiEyeOff,
  "fi:file": FiFile,
  "fi:file-text": FiFileText,
  "fi:filter": FiFilter,
  "fi:globe": FiGlobe,
  "fi:home": FiHome,
  "fi:image": FiImage,
  "fi:info": FiInfo,
  "fi:italic": FiItalic,
  "fi:list": FiList,
  "fi:loader": FiLoader,
  "fi:lock": FiLock,
  "fi:mail": FiMail,
  "fi:map-pin": FiMapPin,
  "fi:menu": FiMenu,
  "fi:message-circle": FiMessageCircle,
  "fi:message-square": FiMessageSquare,
  "fi:more-vertical": FiMoreVertical,
  "fi:mouse-pointer": FiMousePointer,
  "fi:phone": FiPhone,
  "fi:paperclip": FiPaperclip,
  "fi:play": FiPlay,
  "fi:plus": FiPlus,
  "fi:refresh-cw": FiRefreshCw,
  "fi:rotate-ccw": FiRotateCcw,
  "fi:save": FiSave,
  "fi:search": FiSearch,
  "fi:send": FiSend,
  "fi:settings": FiSettings,
  "fi:share-2": FiShare2,
  "fi:shield": FiShield,
  "fi:shopping-bag": FiShoppingBag,
  "fi:sliders": FiSliders,
  "fi:smile": FiSmile,
  "fi:tag": FiTag,
  "fi:target": FiTarget,
  "fi:trash-2": FiTrash2,
  "fi:trending-up": FiTrendingUp,
  "fi:truck": FiTruck,
  "fi:user": FiUser,
  "fi:user-check": FiUserCheck,
  "fi:users": FiUsers,
  "fi:x": FiX,
  "fi:zap": FiZap,

  // Simple Icons
  "si:bitcoin": SiBitcoin,
  "si:shopify": SiShopify,
  "si:woocommerce": SiWoo,
};
